services:
  app:
    build: 
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "5555:5555"
      - "8002:8002"
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      CHOKIDAR_USEPOLLING: true
      NODE_ENV: development
      DATABASE_URL: ${DATABASE_URL}
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - develop_network

  db:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    env_file:
      - .env
    networks:
      - develop_network

volumes:
  mysql_data:

networks:
  develop_network:
    driver: bridge